DROP TABLE class_hospitais21 CASCADE CONSTRAINTS;

DROP TABLE dadosaude20 CASCADE CONSTRAINTS;

DROP TABLE dadossaude21 CASCADE CONSTRAINTS;

DROP TABLE hospitais CASCADE CONSTRAINTS;

DROP TABLE hospitais21 CASCADE CONSTRAINTS;
